In [2]:
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import TfidfVectorizer
import datetime
import pandas as pd

In [3]:
data = pd.read_csv("result.csv")

In [4]:
data

,text,anger,disgust,fear,joy,sadness,surprise,no emotion
0,The kitchen stinks .,0,1,0,0,0,0,0
1,I'll throw out the garbage .,0,0,0,0,0,0,1
2,"So Dick , how about getting some coffee for to...",0,0,0,1,0,0,0
3,Coffee ? I don ’ t honestly like that kind of ...,0,1,0,0,0,0,0
4,"Come on , you can at least try a little , besi...",0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...
226119,Succesfully following Tayla!!,0,0,0,1,0,0,0
226120,Happy Mothers Day All my love,0,0,0,1,0,0,0
226121,Happy Mother's Day to all the mommies out ther...,0,0,0,1,0,0,0
226122,WASSUP BEAUTIFUL!!! FOLLOW ME!! PEEP OUT MY N...,0,0,0,1,0,0,0
226123,bullet train from tokyo the gf and i have b...,0,0,0,1,0,0,0

In [5]:
len(data)

226124

In [6]:
vect = TfidfVectorizer()
tfvect = vect.fit_transform(data["text"])

In [ ]:
X = tfvect.todense()

In [44]:
def model(target_words, n): #텍스트 인풋, 원하는 유사문장 개수를 argument로 입력

    print("...유사 문장 추출을 시작합니다...\n")
    target_words = [target_words]
     
    ### 입력된 문장에 대해
            

    ### 해당 문장을 벡터화
    vect_temp = vect.transform(target_words)

    ### 벡터화된 words에 대해서 트레인 데이터를 유사도 순으로 정렬
    sim_index = cosine_similarity(vect_temp,tfvect).argsort()[:,::-1][0]

    ### 정렬된 순서로 모집중 챌린지 데이터프레임 가져옴
    most_sim_df = data.iloc[sim_index]

    ### argument에 입력된 챌린지는 자기자신으로 추천되면 안되므로 포함될 경우 제외
    most_sim_df=most_sim_df.reset_index(drop=True)[:n]
    result = most_sim_df

                  
    print("유사 문장 추출 완료!\n")
    print("---------------------------")
    print("유사 문장 추출 결과:\n")
    for i in most_sim_df["text"]:
        print("\t"+i)
    return result

In [45]:
model("it really is too bad that tmrw is sunday and monday is a holiday hahahah",6)

...유사 문장 추출을 시작합니다...

유사 문장 추출 완료!

---------------------------
유사 문장 추출 결과:

	that is bad
	hahahah Thank you  Feel the Love
	morning... on Monday. Is it really?
	It is too bad today .
	It really is .
	is that too bad though ?

,text,anger,disgust,fear,joy,sadness,surprise,no emotion
0,that is bad,0,1,0,0,0,0,0
1,hahahah Thank you Feel the Love,0,0,0,0,0,0,1
2,morning... on Monday. Is it really?,0,0,0,0,0,0,1
3,It is too bad today .,0,0,0,0,0,0,1
4,It really is .,0,0,0,0,0,0,1
5,is that too bad though ?,0,0,0,0,0,1,0